# Generated by Django 5.2.2 on 2025-06-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Unkown', max_length=150),
            preserve_default=False,
        ),
    ]
