# Generated by Django 5.2.2 on 2025-06-26 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muster',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='muster',
            name='user',
        ),
        migrations.AddField(
            model_name='muster',
            name='employee',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
