# Generated by Django 5.2.2 on 2025-06-26 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_muster_employee_id_remove_muster_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muster',
            name='employee',
        ),
        migrations.AddField(
            model_name='muster',
            name='employee_id',
            field=models.CharField(default='2', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='muster',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
