# Generated by Django 5.2.2 on 2025-07-07 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_employee_cover_picture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company_check',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
